version: "3.7"

services:
  db:
    container_name: mva_db
    build:
      context: ./docker-postgis
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/data/:/mnt/
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - mine

#  app:
#    container_name: mva_app
#    build:
#      context: ./docker-rshiny
#    # image: fineprint/mva
#    restart: always
#    ports:
#      - ${SHINY_PORT}:80
#    volumes:
#      - ./app:/srv/shiny-server
#    networks:
#      - mine

volumes:
  pgdata:
    driver: local

networks:
  mine:
    name: mine